language: java
jdk: openjdk11
branches:
  only:
    - develop
    - "/^release-[0-999].[0-999]$/"
    - master
notifications:
  email:
    recipients:
      - tylercherield@gmail.com
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
 -Dsonar.organization=miw-upm-github -Dsonar.login=$SONAR